name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean up previous worktree folder
        run: |
          rm -rf github-pages-deploy-action-temp-deployment-folder
          git worktree prune

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: ./
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes to remove temp folder
        run: |
          git rm -r --cached github-pages-deploy-action-temp-deployment-folder
          git commit -m "Remove temporary deployment folder"
          git push
