name: PR Deployment to GitHub Pages

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  deploy-to-pr-preview:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the PR branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}  # Get the PR source branch (e.g., feature branch)

    - name: Deploy to GitHub Pages (using the PR source branch)
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: prbranch  # Deploy to the main branch of your GitHub Pages repository (will not overwrite the main production)
        folder: .  # The root directory of your project
        cname: pr-${{ github.event.pull_request.number }}.aka-pharande.github.io  # Unique URL for each PR

    - name: Clean up PR preview (optional)
      if: github.event.pull_request.merged == true
      run: echo "Clean up the preview environment if needed"
